apiVersion: v1
kind: Service
metadata:
  name: angular-example-service
spec:
  selector:
    app: angular-example
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
    - protocol: TCP
      port: 443
      targetPort: 443
